-- =============================================================================
-- HOUSEONE SEED DATA: EASTERN NIGERIAN LOCATIONS, AGENTS & VERIFIED PROPERTIES
-- =============================================================================
-- Focus: Eastern Nigeria (Enugu, Anambra, Imo, Abia, and Delta Asaba Gateway)
-- Compliant with HouseOne BRD v1.0 & Fee Engine Specifications
-- =============================================================================

-- 1. SEED EASTERN NIGERIAN LOCATIONS & ENCLAVES
INSERT INTO public.nigerian_locations (state, lga, area, popular_landmarks) VALUES
-- Enugu State (Coal City)
('Enugu', 'Enugu North', 'Independence Layout', ARRAY['Government House', 'Presidential Boulevard', 'Okpara Square', 'Hotel Presidential']),
('Enugu', 'Enugu North', 'Enugu GRA', ARRAY['Polo Park Mall', 'Enugu Golf Course', 'State High Court']),
('Enugu', 'Enugu North', 'New Haven', ARRAY['Chime Avenue', 'Roban Stores', 'Upper Chime']),
('Enugu', 'Enugu East', 'Trans-Ekulu', ARRAY['Damija Phase 1 & 2', 'Nowas Junction', 'Ekulu River Bridge']),
('Enugu', 'Enugu East', 'Abakpa Nike', ARRAY['Liberty Bus Stop', 'T-Junction', 'Nike Lake Resort']),
('Enugu', 'Enugu South', 'Achara Layout', ARRAY['Agbani Road', 'Topland Bus Stop', 'One Day Road']),
('Enugu', 'Nsukka', 'UNN Campus / University Road', ARRAY['UNN First Gate', 'Odenigbo', 'Peace Mass Transit Park']),

-- Anambra State (Commercial & Capital Hubs)
('Anambra', 'Onitsha North', 'GRA Onitsha', ARRAY['All Hallows Seminary', 'DMGS Onitsha', 'Bisi Emodi Way', 'Ridgeway Road']),
('Anambra', 'Onitsha North', 'Inland Town', ARRAY['Obi of Onitsha Palace', 'Ime Obi', 'Awka Road']),
('Anambra', 'Onitsha South', 'Fegge', ARRAY['Port Harcourt Road', 'Main Market Axis', 'Zik Avenue']),
('Anambra', 'Oyi', '3-3 Nkwelle Ezunaka', ARRAY['Federal Housing Estate', 'St. Charles Borromeo Hospital Axis', 'Trans-Nkisi Link']),
('Anambra', 'Idemili North', 'Ogidi / Nkpor', ARRAY['Building Materials Market', 'Tarzan Junction', 'Afor Nkpor']),
('Anambra', 'Awka South', 'Ngozika Housing Estate', ARRAY['Ngozika Phase 1 & 2', 'Rockland Estate', 'Executive Enclave']),
('Anambra', 'Awka South', 'Iyi-Agu Estate', ARRAY['Government House Awka', 'Ekwueme Square', 'Roban Stores Awka']),
('Anambra', 'Awka South', 'Ifite Awka', ARRAY['UNIZIK Perm Site First Gate', 'School Gate', 'Book Foundation']),
('Anambra', 'Nnewi North', 'Otolo / Nnewi Industrial', ARRAY['Innoson Vehicle Plant', 'Nnewi Motor Parts Market', 'Chicason Group']),

-- Imo State (Heartland)
('Imo', 'Owerri West', 'New Owerri', ARRAY['Area A-H Housing', 'Concorde Boulevard', 'Heroes Square', 'World Bank Estate']),
('Imo', 'Owerri Municipal', 'Ikenegbu Layout', ARRAY['Ikenegbu Extension', 'Tetlow Road', 'Wetheral Road']),
('Imo', 'Owerri Municipal', 'Works Layout', ARRAY['Federal University of Technology Guest House', 'IMSUTH Axis']),
('Imo', 'Owerri Municipal', 'Aladinma', ARRAY['Aladinma Shopping Mall', 'IMSU Back Gate', 'Federal Polytechnic']),
('Imo', 'Owerri North', 'Orji / Uratta', ARRAY['Orji Flyover', 'Owerri-Okigwe Expressway', 'Toronto Junction']),
('Imo', 'Orlu', 'Orlu Urban', ARRAY['Orlu Teaching Hospital', 'Banana Junction', 'International Market']),

-- Abia State (Enyimba City & Capital)
('Abia', 'Aba North', 'Aba GRA', ARRAY['Brass Junction', 'Abia State Polytechnic Axis', 'Faulks Road']),
('Abia', 'Aba North', 'Umungasi', ARRAY['Commercial Corridor', 'MCC Road', 'Union Bank Axis']),
('Abia', 'Aba South', 'Asa Road / Eziukwu', ARRAY['Ariaria International Market Gateway', 'Aba Sports Club']),
('Abia', 'Umuahia North', 'GRA Umuahia', ARRAY['Government House Umuahia', 'Okpara Auditorium', 'Bank Road']),

-- Delta State (East Niger Bridge Gateway)
('Delta', 'Oshimili South', 'Asaba GRA', ARRAY['Government House Asaba', 'Summit Road', 'Grand Hotel', 'Inter-Bau Roundabout']),
('Delta', 'Oshimili South', 'Cable Point / Waterfront', ARRAY['Niger Bridge Toll Plaza', 'River Niger Waterfront', 'Marine Road']);

-- 2. SEED VERIFIED EASTERN NIGERIAN PROPERTIES (Reflects HouseOne BRD)
INSERT INTO public.properties (
    id,
    title,
    slug,
    description,
    property_type,
    listing_status,
    verification_status,
    is_verified,
    is_featured,
    state,
    lga,
    area,
    street_address,
    landmark,
    bedrooms,
    bathrooms,
    toilets,
    parking_spaces,
    size_sqm,
    is_serviced,
    is_furnished,
    rent_price,
    service_charge,
    caution_fee,
    legal_fee_pct,
    agency_fee_pct,
    total_upfront_estimate,
    cover_image_url,
    amenities
) VALUES
(
    '00000000-0000-0000-0000-000000000001',
    'Grand 5-Bedroom Executive Mansion + BQ',
    'luxury-5-bed-mansion-independence-layout-enugu',
    'Experience elevated contemporary luxury in this masterfully crafted 5-bedroom executive mansion situated in the prestigious diplomatic quarter of Independence Layout, Enugu (Coal City). Dedicated 24/7 solar/generator power and industrial borehole plant.',
    'duplex',
    'active',
    'approved',
    true,
    true,
    'Enugu',
    'Enugu North',
    'Independence Layout',
    'Plot 14, Presidential Boulevard, Independence Layout',
    'Near Enugu Government House & Okpara Square',
    5,
    5,
    6,
    4,
    450,
    true,
    false,
    8500000,
    1000000,
    500000,
    10.00,
    10.00,
    11700000,
    '/images/hero-eastern-nigerian-mansion.jpg',
    ARRAY['24/7 Power Backup (Gen + Solar)', 'Industrial Borehole Water Plant', 'Gated Diplomatic Zone Security', 'CCTV & Video Intercom', 'Motorized Security Gate', '2-Room Staff Quarters (BQ)', 'Interlocking Stone Driveway']
),
(
    '00000000-0000-0000-0000-000000000002',
    'Contemporary 5-Bedroom Luxury Duplex',
    'contemporary-5-bed-duplex-gra-onitsha',
    'Prestigious contemporary residence in prime GRA Onitsha with cantilevered glass balcony, marble finishings, motorized security gate, and high perimeter electrified fence.',
    'duplex',
    'active',
    'approved',
    true,
    true,
    'Anambra',
    'Onitsha North',
    'GRA Onitsha',
    'Ridgeway Drive, GRA Onitsha',
    'Near All Hallows Seminary & DMGS Axis',
    5,
    5,
    5,
    3,
    380,
    true,
    false,
    6000000,
    800000,
    400000,
    10.00,
    10.00,
    8400000,
    '/images/onitsha-gra-mansion.jpg',
    ARRAY['Dedicated Transformer', 'Industrial Borehole with Water Treatment', 'Electrified Security Fence', 'Glass Balcony', 'Interlocking Stone Compound']
),
(
    '00000000-0000-0000-0000-000000000003',
    'Executive 4-Bedroom Serviced Duplex',
    'executive-4-bed-duplex-new-owerri',
    'Mastercrafted 4-bedroom executive duplex in New Owerri featuring dark stone-coated Milano roofing, grand pillars, balcony, and serene residential gated neighborhood.',
    'duplex',
    'active',
    'approved',
    true,
    true,
    'Imo',
    'Owerri West',
    'New Owerri',
    'Plot 14, Plymouth Crescent, Area B, New Owerri',
    'Off Concorde Boulevard & Heroes Square',
    4,
    4,
    5,
    3,
    320,
    true,
    false,
    4500000,
    600000,
    350000,
    10.00,
    10.00,
    6350000,
    '/images/owerri-new-duplex.jpg',
    ARRAY['Estate Gen Backup', 'Borehole Water Facility', 'High Perimeter Wall', 'Covered Carport', 'En-suite Bedrooms']
),
(
    '00000000-0000-0000-0000-000000000004',
    'Contemporary 4-Bedroom Duplex with Carport',
    'contemporary-4-bed-duplex-ngozika-estate-awka',
    'Modern duplex in the serene, gated Ngozika Housing Estate in Awka Capital. Features dark aluminum parapet fascia, vertical wooden slat accents, bronze solar tint windows, and covered parking.',
    'duplex',
    'active',
    'approved',
    true,
    false,
    'Anambra',
    'Awka South',
    'Ngozika Housing Estate',
    'Road 4, Ngozika Housing Estate Phase 2, Awka',
    'Near Government House & Ekwueme Square',
    4,
    4,
    4,
    2,
    260,
    true,
    false,
    4200000,
    500000,
    300000,
    10.00,
    10.00,
    5840000,
    '/images/awka-ngozika-duplex.jpg',
    ARRAY['Gated Estate Security', 'Solar Inverter Ready', 'Borehole Water Supply', 'Covered Carport', 'Paved Access Road']
),
(
    '00000000-0000-0000-0000-000000000005',
    'Luxury 4-Bedroom Detached Duplex + BQ',
    'luxury-4-bed-duplex-independence-layout-enugu',
    'Spacious detached executive duplex in Independence Layout Enugu with manicured landscaping, dedicated transformer, and domestic staff quarters.',
    'duplex',
    'active',
    'approved',
    true,
    false,
    'Enugu',
    'Enugu North',
    'Independence Layout',
    'Plot 18, Independence Layout, Enugu',
    'Near ESUT Business School & Hotel Presidential',
    4,
    4,
    5,
    3,
    280,
    true,
    false,
    5500000,
    700000,
    400000,
    10.00,
    10.00,
    7700000,
    '/images/enugu-flagship-mansion.jpg',
    ARRAY['24/7 Security Patrol', 'Solar Inverter Backup', 'Treated Water', 'En-suite Rooms', '1-Room BQ']
),
(
    '00000000-0000-0000-0000-000000000006',
    'Prestigious 5-Bedroom Villa in Aba GRA',
    'prestigious-5-bed-villa-aba-gra',
    'Contemporary stone-veneer duplex villa located in the quiet diplomatic enclave of Aba GRA. Features wide interlocking driveway, generator shelter, and CCTV surveillance.',
    'duplex',
    'active',
    'approved',
    true,
    false,
    'Abia',
    'Aba North',
    'Aba GRA',
    'Plot 7, Commercial Avenue, Aba GRA',
    'Near Brass Junction & Abia State Poly',
    5,
    5,
    6,
    4,
    360,
    true,
    false,
    4800000,
    600000,
    350000,
    10.00,
    10.00,
    6710000,
    '/images/aba-gra-residence.jpg',
    ARRAY['Perimeter Razor Wire', 'High-Yield Borehole', 'Generator House', 'CCTV Security', 'Granite Wall Accents']
);
